lint-frontend:
	make -C frontend lint

install:
	make -C frontend install

start-frontend:
	make -C frontend start

start-backend:
	npx start-server -s ./frontend/dist

start:
	make -C frontend start

develop:
	make start-backend & make start-frontend

build:
	rm -rf frontend/dist
	make -C frontend build